source 'https://rubygems.org'

 	gem 'rspec'
 	gem 'capybara'
 	gem 'pry'
 	gem 'devise'
 	gem 'allure-rspec'
 	gem 'open3'
	gem 'capybara-screenshot'
 	gem 'selenium-webdriver'
 	gem 'webdrivers'
 	gem 'testrail-rspec'
 	gem 'rest-client'
 	gem 'clipboard'
 	gem 'parallel_tests'
 	gem 'parallel_split_test'
 	gem 'knapsack'
 	gem 'ruby-kafka'
 	gem 'cnvrg'
 	gem 'colorize'
 	gem 'guerrilla_mailX', '~> 0.1.0'
 	gem 'mailinator'
 	gem 'mailinator_client'
 	gem 'kubeclient'
 	gem 'multipart-post'
	gem 'activesupport'
	gem 'google_drive'
	gem 'aws-sdk'
