name: Trigger Jenkins Job

on:
  push:
    branches:
      - main  # Replace with your desired branch name

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Trigger Jenkins Job
        run: |
          curl -X POST \
            -u 'sagar':'806aec7e04f04d228e2df0555d14f1f9' \
            "http://192.168.0.110:8080/job/test-pipeline/build" \
            -d token='xlzb85dc7kqo3lne'  # Update this with your trigger token

