name: Ruby Docker Automation

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my-ruby-app .

      - name: Run Ruby in Docker
        run: docker run my-ruby-app ruby your_ruby_script.rb
