name: Ruby Automation in Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: actions/setup-docker@v2

    - name: Build Docker image
      run: docker build -t my-ruby-app .

    - name: Run Ruby automation in Docker
      run: docker run my-ruby-app ruby /path/to/your/ruby_script.rb
