name: Trigger Jenkins Job

on:
  push:
    branches:
      - main  # You can specify the branch you want to trigger the job on

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: trigger single Job
        uses: appleboy/jenkins-action@master
        with:
          url: "http://192.168.0.110:8080/job/test-pipeline/build"
          user: "sagar"
          token: "1197d1e587f8cc493564a38f4481bba22e"
          job: "test-pipeline"
