name: Trigger Jenkins Job

on:
  pull_request:
    types:
      - opened
    branches:
      - call-back

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Trigger Jenkins Job
        env:
          JENKINS_URL: 'https://37b1-54-171-143-46.ngrok-free.app'
          JENKINS_USERNAME: 'sagar'
          JENKINS_API_TOKEN: '111ea0484fe649f3fbfad26d2763d30060'
        run: |
          response=$(curl -X POST "$JENKINS_URL/job/test-pipeline/build" --user $JENKINS_USERNAME:$JENKINS_API_TOKEN)
          echo "Response from Jenkins: $response"
